"""Business constants for HOS assumptions."""

DEFAULT_SHIFT_START_HOUR = 6
FUEL_STOP_DISTANCE_MILES = 1000
FUEL_STOP_DURATION_MINUTES = 30
PICKUP_DURATION_MINUTES = 60
DROPOFF_DURATION_MINUTES = 60
BREAK_DURATION_MINUTES = 30
RESET_DURATION_MINUTES = 10 * 60
MAX_DRIVING_PER_SHIFT_MINUTES = 11 * 60
MAX_SHIFT_WINDOW_MINUTES = 14 * 60
BREAK_REQUIRED_AFTER_DRIVING_MINUTES = 8 * 60
MAX_CYCLE_ON_DUTY_MINUTES = 70 * 60
