# Generated by Django 6.0.4 on 2026-04-16 07:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location_text', models.CharField(max_length=255)),
                ('pickup_location_text', models.CharField(max_length=255)),
                ('dropoff_location_text', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_distance_miles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_raw_drive_duration_minutes', models.IntegerField(default=0)),
                ('trip_status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveIntegerField()),
                ('segment_type', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty Not Driving')], max_length=32)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('location_context', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_segments', to='trips.trip')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('break', 'Break'), ('overnight_reset', 'Overnight Reset')], max_length=32)),
                ('sequence', models.PositiveIntegerField()),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('planned_arrival', models.DateTimeField(blank=True, null=True)),
                ('planned_departure', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_trip_stop_sequence')],
            },
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('start_name', models.CharField(max_length=255)),
                ('end_name', models.CharField(max_length=255)),
                ('distance_miles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.IntegerField()),
                ('geometry_geojson', models.JSONField(blank=True, default=dict)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_legs', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_trip_leg_sequence')],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('total_miles', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('off_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sleeper_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['log_date'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'log_date'), name='unique_trip_log_date')],
            },
        ),
    ]
