# Generated by Django 6.0.4 on 2026-04-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='log_entries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
